version: "3.9"

services:
  my-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:80"

  my-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment:
      - SERVER_HOST=my-server
    depends_on:
      - my-server
