services:
  my-server:
    build:
      context: ./server
    ports:
      - "8000:80"

  my-client:
    build:
      context: ./client
    environment:
      - SERVER_HOST=my-server
    depends_on:
      - my-server
